In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\danie\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\danie\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
# Importando as bibliotecas que serão utilizadas

import pandas as pd

In [3]:
# Fazendo as configurações dentro da biblioteca

pd.set_option("display.max_columns",None) # Isso mostra todas as colunas, quando chamarmos a tabela (DataFrame)

In [4]:
#Definindo a varíavel "dados"
dados = pd.read_csv("Spotify most streamed.csv",encoding="utf-8")

In [5]:
#Chamando o nosso DataFrame

dados.head()

                    Artist and Title        Streams      Daily
0       The Weeknd - Blinding Lights  3,783,983,806  1,736,378
1          Ed Sheeran - Shape of You  3,616,649,759  1,135,140
2  Lewis Capaldi - Someone You Loved  2,958,875,491  1,522,093
3            Post Malone - Sunflower  2,898,311,408  1,871,177
4         Tones And I - Dance Monkey  2,896,024,418    666,818

In [6]:
#Realizando a análise exploratória 

dados.shape

(2500, 3)

In [7]:
dados.dtypes

Artist and Title    object
Streams             object
Daily               object
dtype: object

In [8]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist and Title  2500 non-null   object
 1   Streams           2500 non-null   object
 2   Daily             2497 non-null   object
dtypes: object(3)
memory usage: 58.7+ KB

In [9]:
#Verificando a quantidade de linhas com valores nulos
dados.isnull().sum()

Artist and Title    0
Streams             0
Daily               3
dtype: int64

#### **Dados nulos**

Identificamos que em nosso data Frame , possuímos alguns valores nulos, ou seja, valores que não existem ou não vieram na base de dados.
Iremos realizar as tratativas, mais para frente.

In [31]:
#Verificando se há duplicidade

dados.duplicated().sum()

np.int64(0)

In [10]:
#REALIZANDO OS PRIMEIROS AJUSTES NA TABELA , SEPARANDO POR COLUNA "ARTISTA" E "MÚSICA"

dados[["Artist","Song"]] = dados["Artist and Title"].str.split(" - ",n=1,expand=True)

In [11]:
dados.head()

,Artist and Title,Streams,Daily,Artist,Song
0,The Weeknd - Blinding Lights,"3,783,983,806","1,736,378",The Weeknd,Blinding Lights
1,Ed Sheeran - Shape of You,"3,616,649,759","1,135,140",Ed Sheeran,Shape of You
2,Lewis Capaldi - Someone You Loved,"2,958,875,491","1,522,093",Lewis Capaldi,Someone You Loved
3,Post Malone - Sunflower,"2,898,311,408","1,871,177",Post Malone,Sunflower
4,Tones And I - Dance Monkey,"2,896,024,418","666,818",Tones And I,Dance Monkey

In [12]:
#Excluindo a primeira coluna

dados.drop(columns="Artist and Title",axis=1,inplace=True)

In [13]:
dados.head()

         Streams      Daily         Artist               Song
0  3,783,983,806  1,736,378     The Weeknd    Blinding Lights
1  3,616,649,759  1,135,140     Ed Sheeran       Shape of You
2  2,958,875,491  1,522,093  Lewis Capaldi  Someone You Loved
3  2,898,311,408  1,871,177    Post Malone          Sunflower
4  2,896,024,418    666,818    Tones And I       Dance Monkey

In [14]:
#Definindo a ordem das colunas

dados = dados[["Artist","Song","Streams","Daily"]]

In [15]:
#Verificando o nosso DataFrame

dados.head()

          Artist               Song        Streams      Daily
0     The Weeknd    Blinding Lights  3,783,983,806  1,736,378
1     Ed Sheeran       Shape of You  3,616,649,759  1,135,140
2  Lewis Capaldi  Someone You Loved  2,958,875,491  1,522,093
3    Post Malone          Sunflower  2,898,311,408  1,871,177
4    Tones And I       Dance Monkey  2,896,024,418    666,818

#### **Ajustando as informações do nosso DataFrame**

Como o nosso DataFrame é grande, possuindo muitas linhas, iremos deixar alguns ajustes, padronizando as informações.

In [16]:
#Ajustes na coluna Artist

dados["Artist"] = dados["Artist"].str.strip().str.title() #Tirando os espaços e padronizando as informações, padronizando sempre o ínicio da palavra com maiúsculo
dados.head()

          Artist               Song        Streams      Daily
0     The Weeknd    Blinding Lights  3,783,983,806  1,736,378
1     Ed Sheeran       Shape of You  3,616,649,759  1,135,140
2  Lewis Capaldi  Someone You Loved  2,958,875,491  1,522,093
3    Post Malone          Sunflower  2,898,311,408  1,871,177
4    Tones And I       Dance Monkey  2,896,024,418    666,818

In [17]:
dados["Song"] = dados["Song"].str.strip().str.title()
dados.head()

          Artist               Song        Streams      Daily
0     The Weeknd    Blinding Lights  3,783,983,806  1,736,378
1     Ed Sheeran       Shape Of You  3,616,649,759  1,135,140
2  Lewis Capaldi  Someone You Loved  2,958,875,491  1,522,093
3    Post Malone          Sunflower  2,898,311,408  1,871,177
4    Tones And I       Dance Monkey  2,896,024,418    666,818

In [18]:
#Modificando o tipo de dados da coluna "Streams" - a mesma está em formato de string

print(dados["Streams"].dtype) # o resultado traz "objetc"
dados["Streams"] = pd.to_numeric(dados["Streams"].str.replace(",",""),errors="coerce").astype(float)

object

In [19]:
dados.head()

          Artist               Song       Streams      Daily
0     The Weeknd    Blinding Lights  3.783984e+09  1,736,378
1     Ed Sheeran       Shape Of You  3.616650e+09  1,135,140
2  Lewis Capaldi  Someone You Loved  2.958875e+09  1,522,093
3    Post Malone          Sunflower  2.898311e+09  1,871,177
4    Tones And I       Dance Monkey  2.896024e+09    666,818

In [20]:
#alterando o tipo da coluna "Streams"

dados["Streams"] = dados["Streams"].astype("Int64")

In [21]:
dados.head()

          Artist               Song     Streams      Daily
0     The Weeknd    Blinding Lights  3783983806  1,736,378
1     Ed Sheeran       Shape Of You  3616649759  1,135,140
2  Lewis Capaldi  Someone You Loved  2958875491  1,522,093
3    Post Malone          Sunflower  2898311408  1,871,177
4    Tones And I       Dance Monkey  2896024418    666,818

#### **Verificando A coluna "Daily"**

Como havíamos verificado, a coluna Daily possui alguns valores nulos. Iremos seguir com o tratamento desses valores.

In [22]:
#verificando os valores nulos

filtro = dados[dados["Daily"].isna()]
print(filtro[["Artist","Song","Streams","Daily"]])

                 Artist           Song    Streams Daily
1223           Lil Tjay            F.N  624709072   NaN
1943            Unknown  Forever Young  474001972   NaN
2251  Various Artists -           None  430691356   NaN

In [23]:
#Outro jeito de verificar

filtro2 = dados.loc[dados["Daily"].isna(),["Artist","Song","Streams","Daily"]]
filtro2

                 Artist           Song    Streams Daily
1223           Lil Tjay            F.N  624709072   NaN
1943            Unknown  Forever Young  474001972   NaN
2251  Various Artists -           None  430691356   NaN

#### **Realizando a limpeza da coluna "Daily"**

Como não temos a quantidade de reproduções diárias para esses artistas, e faltam algumas informações, vamos remover essas linhas da nossa base de dados.

In [24]:
#Retirando essas linhas que não possuem informação "Daily"

dados = dados.dropna(subset=["Daily"])

In [25]:
#Verificando agora

dados.isnull().sum()

Artist     0
Song       0
Streams    0
Daily      0
dtype: int64

In [26]:
#Formatando a coluna "Daily".Mudando o tipo 

print(dados["Daily"].dtype) # O resultado é "object"

dados["Daily"] = pd.to_numeric(dados["Daily"].str.replace(",","").astype("Int64"))

object

#### **Como sabemos que o nosso DataFrame não é uma cópia, por hora, iremos ignorar esse aviso.**

In [27]:
print(dados["Daily"].dtype)

Int64

In [28]:
#Verificando o nosso DataFrame

dados.head()

          Artist               Song     Streams    Daily
0     The Weeknd    Blinding Lights  3783983806  1736378
1     Ed Sheeran       Shape Of You  3616649759  1135140
2  Lewis Capaldi  Someone You Loved  2958875491  1522093
3    Post Malone          Sunflower  2898311408  1871177
4    Tones And I       Dance Monkey  2896024418   666818

In [29]:
# SALVANDO O NOVO DataFrame

dados.to_excel("Dados_limpos.xlsx",index=False)